name: development
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.1
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: qwerty

      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: "false"

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    volumes:
      - kc_data:/opt/keycloak/data
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json

volumes:
  kc_data:
